import React, { useMemo, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { ALL_TENANTS } from '../lib/mockData';
import {
  Bot,
  CheckCircle2,
  Clock3,
  FileSpreadsheet,
  Filter,
  Search,
  UserRoundCheck,
} from 'lucide-react';

const ORDER_ROWS = [
  {
    ticket_no: 'TKT-2026-0001',
    tenant_id: 'tenant-001',
    order_id: 'ORD-1007',
    customer: 'Maya Optical Store',
    channel: 'WhatsApp',
    item: 'BlueCut 1.56 lens',
    quantity: 10,
    status: 'Reserved',
    order_source: 'ai_generated',
    assignee: 'Samuhik AI',
    resolution: 'AI extracted order and reserved stock',
    created_at: '2026-04-30 10:22',
  },
  {
    ticket_no: 'TKT-2026-0002',
    tenant_id: 'tenant-002',
    order_id: 'ORD-1008',
    customer: 'Kathmandu Fashion Hub',
    channel: 'Instagram',
    item: 'Cotton kurta set',
    quantity: 2,
    status: 'Awaiting payment',
    order_source: 'human_agent',
    assignee: 'Ram Shrestha',
    resolution: 'Manual quote sent after size confirmation',
    created_at: '2026-04-30 11:05',
  },
  {
    ticket_no: 'TKT-2026-0003',
    tenant_id: 'tenant-001',
    order_id: 'ORD-1009',
    customer: 'Retail Walk-in Lead',
    channel: 'Messenger',
    item: 'Eye checkup appointment',
    quantity: 1,
    status: 'Scheduled',
    order_source: 'ai_generated',
    assignee: 'Samuhik AI',
    resolution: 'AI created appointment ticket',
    created_at: '2026-04-30 12:40',
  },
];

const SourceBadge = ({ source }) => {
  const isAi = source === 'ai_generated';
  return (
    <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${
      isAi ? 'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-100' : 'bg-blue-50 text-blue-700 ring-1 ring-blue-100'
    }`}>
      {isAi ? <Bot className="h-3 w-3" /> : <UserRoundCheck className="h-3 w-3" />}
      {isAi ? 'AI Generated' : 'Human Agent'}
    </span>
  );
};

const statusClasses = {
  Reserved: 'bg-emerald-50 text-emerald-700 ring-emerald-100',
  'Awaiting payment': 'bg-amber-50 text-amber-700 ring-amber-100',
  Scheduled: 'bg-indigo-50 text-indigo-700 ring-indigo-100',
};

const Orders = () => {
  const { profile } = useAuth();
  const [sourceFilter, setSourceFilter] = useState('all');
  const [tenantFilter, setTenantFilter] = useState('all');
  const [query, setQuery] = useState('');
  const tenants = profile?.role === 'super_admin' ? ALL_TENANTS : [];

  const filteredRows = useMemo(() => {
    return ORDER_ROWS.filter((row) => {
      const matchesSource = sourceFilter === 'all' || row.order_source === sourceFilter;
      const matchesTenant = tenantFilter === 'all' || row.tenant_id === tenantFilter;
      const haystack = `${row.ticket_no} ${row.order_id} ${row.customer} ${row.item} ${row.channel}`.toLowerCase();
      return matchesSource && matchesTenant && haystack.includes(query.toLowerCase());
    });
  }, [query, sourceFilter, tenantFilter]);

  return (
    <div className="mx-auto w-full max-w-7xl p-6 lg:p-8">
      <div className="mb-8 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Store Admin</p>
          <h2 className="mt-1 text-2xl font-bold text-slate-900">Orders & Ticket Spreadsheet</h2>
          <p className="mt-1 text-sm text-slate-500">
            Track tickets generated by the LLM and orders finalized by human agents.
          </p>
        </div>
        <div className="grid grid-cols-3 gap-3">
          <div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm">
            <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Tickets</p>
            <p className="mt-1 text-2xl font-bold text-slate-900">{ORDER_ROWS.length}</p>
          </div>
          <div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm">
            <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">AI Orders</p>
            <p className="mt-1 text-2xl font-bold text-emerald-600">{ORDER_ROWS.filter((row) => row.order_source === 'ai_generated').length}</p>
          </div>
          <div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm">
            <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Human</p>
            <p className="mt-1 text-2xl font-bold text-blue-600">{ORDER_ROWS.filter((row) => row.order_source === 'human_agent').length}</p>
          </div>
        </div>
      </div>

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div className="flex flex-col gap-3 border-b border-slate-200 bg-slate-50/70 px-5 py-4 lg:flex-row lg:items-center lg:justify-between">
          <div className="flex items-center gap-2">
            <FileSpreadsheet className="h-5 w-5 text-indigo-600" />
            <h3 className="font-bold text-slate-900">Operational Spreadsheet</h3>
          </div>
          <div className="flex flex-col gap-2 sm:flex-row">
            {tenants.length > 0 && (
              <select
                value={tenantFilter}
                onChange={(event) => setTenantFilter(event.target.value)}
                className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold outline-none focus:border-indigo-500"
              >
                <option value="all">All tenants</option>
                {tenants.map((tenant) => (
                  <option key={tenant.id} value={tenant.id}>{tenant.name}</option>
                ))}
              </select>
            )}
            <label className="relative">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
              <input
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                className="h-10 w-full rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-sm outline-none focus:border-indigo-500 sm:w-72"
                placeholder="Search ticket, customer, item"
              />
            </label>
            <label className="relative">
              <Filter className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
              <select
                value={sourceFilter}
                onChange={(event) => setSourceFilter(event.target.value)}
                className="h-10 rounded-xl border border-slate-200 bg-white pl-9 pr-8 text-sm font-semibold outline-none focus:border-indigo-500"
              >
                <option value="all">All sources</option>
                <option value="ai_generated">AI Generated</option>
                <option value="human_agent">Human Agent</option>
              </select>
            </label>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full min-w-[1120px] text-left text-sm">
            <thead className="bg-white text-[11px] uppercase tracking-wider text-slate-500">
              <tr>
                <th className="border-b border-slate-200 px-4 py-3 font-bold">Ticket No</th>
                <th className="border-b border-slate-200 px-4 py-3 font-bold">Order</th>
                <th className="border-b border-slate-200 px-4 py-3 font-bold">Customer</th>
                <th className="border-b border-slate-200 px-4 py-3 font-bold">Channel</th>
                <th className="border-b border-slate-200 px-4 py-3 font-bold">Item</th>
                <th className="border-b border-slate-200 px-4 py-3 font-bold">Qty</th>
                <th className="border-b border-slate-200 px-4 py-3 font-bold">Source</th>
                <th className="border-b border-slate-200 px-4 py-3 font-bold">Status</th>
                <th className="border-b border-slate-200 px-4 py-3 font-bold">Assignee</th>
                <th className="border-b border-slate-200 px-4 py-3 font-bold">Resolution</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredRows.map((row) => (
                <tr key={row.ticket_no} className="hover:bg-slate-50">
                  <td className="px-4 py-4 font-mono text-xs font-bold text-slate-500">{row.ticket_no}</td>
                  <td className="px-4 py-4 font-mono text-xs text-slate-500">{row.order_id}</td>
                  <td className="px-4 py-4 font-semibold text-slate-900">{row.customer}</td>
                  <td className="px-4 py-4">{row.channel}</td>
                  <td className="px-4 py-4">{row.item}</td>
                  <td className="px-4 py-4 font-bold">{row.quantity}</td>
                  <td className="px-4 py-4"><SourceBadge source={row.order_source} /></td>
                  <td className="px-4 py-4">
                    <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ring-1 ${statusClasses[row.status] || 'bg-slate-100 text-slate-700 ring-slate-200'}`}>
                      {row.status === 'Reserved' ? <CheckCircle2 className="h-3 w-3" /> : <Clock3 className="h-3 w-3" />}
                      {row.status}
                    </span>
                  </td>
                  <td className="px-4 py-4">{row.assignee}</td>
                  <td className="px-4 py-4 text-slate-600">{row.resolution}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
};

export default Orders;
